#!/bin/bash
. scripts/functions

GIT_CONFIG_NAME=0
GIT_CONFIG_EMAIL=0
git config --list | grep -q -i 'user.name'
if [ ! $? == 0 ]; then GIT_CONFIG_NAME=1; fi
git config --list | grep -q -i 'user.email'
if [ ! $? == 0 ]; then GIT_CONFIG_EMAIL=1; fi

if [ $GIT_CONFIG_NAME == 1 ] || [ $GIT_CONFIG_EMAIL == 1 ]; then
	echo -e -n " It seems that ${COLOR_Cyan}Git${COLOR_Wipe} is not correctly configured
	Configure ? [Recommended]
	(Y)es, (N)o: "
	
	read choice
	
		case $choice in
		
		[Yy]* )	
			echo
			if [ $GIT_CONFIG_NAME == 1 ]; then
				echo -e -n " Your username: "
				read username
				git config --global user.name $username
			fi
			
			if [ $GIT_CONFIG_EMAIL == 1 ]; then
				echo -n " Your email: "
				read email
				git config --global user.email $email
			fi
			
			echo -e -n "\n Git ${COLOR_Green}properly${COLOR_Wipe} configured"
			exit 0	
			;;
		
		
		[Nn]* )
			echo -e " Git installation... ${COLOR_Cyan}Ignored${COLOR_Wipe}"
			;;
		
		* )
			echo -e " Wrong value... ${COLOR_Cyan}Ignored${COLOR_Wipe}"
			exit 1
			;;
		esac
		
fi

exit 2
