#!/bin/bash
. scripts/functions
clear

# Check if script has root permissions

F_CheckSU

# Check for dependencies

TOOL_DEPENDENCIES="wget tar unzip sed curl"

for package in $TOOL_DEPENDENCIES
do
	if ! dpkg -s "$package" 2>/dev/null | grep -q -i "install ok installed"; then
		echo -e -n  "\n ${COLOR_Yellow}$package$COLOR_Wipe is required to run this tool.
	Install ? [Close if not]
	(Y)es, (N)o: " 
	
	read choice
	
		case $choice in
		
		[Yy]* )
			echo -n -e "\n Installing $package... "
			sudo apt-get -y install $package 2>/dev/null 1>/dev/null
		
			if dpkg -s "$package" 2>/dev/null | grep -q -i "install ok installed"; then
				echo -e "${COLOR_Green}SUCCESS${COLOR_Wipe}\n"
				F_PressEnter
			else
				echo -e "${COLOR_Red}ERROR${COLOR_Wipe}"
				F_PressEnter
				exit 1
			fi
			;;
		* )
			echo -e "\n Exiting...\n"
			exit 1
			;;
		esac
	fi
done
