#!/bin/bash
. scripts/functions    
clear

echo -e "\n Installing SDK... \n$(F_PleaseWait)"

curl -s http://developer.android.com/sdk/index.html > sdk.html
SDK_LINK=$(grep -i linux-tools sdk.html | awk -F'"' '{print $6}')
SDK_ZIPNAME=$(echo $SDK_LINK | awk -F'/' '{print $5}')
rm sdk.html

F_Download $SDK_ZIPNAME $SDK_LINK SDK

# Extract SDK
SDK_Error=0
SDK_Install=0

if [ ! -d "android-sdk-linux" ]; then
	SDK_Install=1
	echo -n -e "\n Extracting SDK... "
	tar zxvf $SDK_ZIPNAME 2>/dev/null 1>/dev/null
	
	if [ $? -eq 0 ]; then
		echo -e "${COLOR_Green}SUCCESS${COLOR_Wipe}"
		sudo chmod -R 777 android-sdk-linux
	else
		echo -e "${COLOR_Red}ERROR${COLOR_Wipe}\n"
		echo -e " ${COLOR_Red}Error when extracting SDK.${COLOR_Wipe}\n"
		F_PressEnter
		exit
	fi
fi

# Download SDK-Tools

curl -s http://dl-ssl.google.com/android/repository/repository-8.xml > sdktools.html
SDKTOOLS_ZIPNAME=$(grep -i build-tools_r sdktools.html | grep -i linux | awk -F'>' '{print $2}' | awk -F'<' '{print $1}' | awk 'END {print}')
SDKTOOLS_LINK="http://dl-ssl.google.com/android/repository/$SDKTOOLS_ZIPNAME"
SDKTOOLS_VERSION=$(echo $SDKTOOLS_ZIPNAME | awk -F'r' '{print $2}'  | awk -F'-' '{print $1}')


F_Download $SDKTOOLS_ZIPNAME $SDKTOOLS_LINK build-tools


# Extract SDK-Tools

if [ ! -d android-sdk-linux/build-tools ]; then
	SDK_Install=1
	echo -n -e "\n Extracting SDK build-tools... "
	mkdir android-sdk-linux/build-tools/$SDKTOOLS_VERSION 2>/dev/null
	unzip -qq -o $SDKTOOLS_ZIPNAME -d android-sdk-linux/build-tools
	
	if [ $? -eq 0 ]; then
		sudo chmod -R 777 android-sdk-linux/build-tools
		mv -f android-sdk-linux/build-tools/* android-sdk-linux/build-tools/$SDKTOOLS_VERSION
		echo -e "${COLOR_Green}SUCCESS${COLOR_Wipe}"
	else
		echo -e "${COLOR_Red}ERROR${COLOR_Wipe}\n"
		echo -e " ${COLOR_Red}Error when extracting SDK build-tools.${COLOR_Wipe}\n"
		SDK_Error=1
	fi
fi


# SDK Platform Tools

PLATFORM_TOOLS="android-tools-adb android-tools-fastboot"

for package in $PLATFORM_TOOLS
do
	if ! dpkg -s "$package" 2>/dev/null | grep -q -i "install ok installed"; then
		SDK_Install=1

		echo -n -e "\n Installing $package... "
		sudo apt-get -y install $package 2>/dev/null 1>/dev/null
		
		if ! dpkg -s "$package" 2>/dev/null | grep -q -i "install ok installed"; then
			echo -e -n "${COLOR_Red}ERROR${COLOR_Wipe}"
			SDK_Error=1
		else
			echo -e -n "${COLOR_Green}SUCCESS${COLOR_Wipe}"
		fi

	fi
done

if [ $SDK_Install == 1 ] && [ $SDK_Error == 0 ]; then
	echo -e "\n\n The installation of the SDK was successful."
elif [ $SDK_Install == 1 ] && [ $SDK_Error == 1 ]; then
	echo -e "\n\n There were one or more errors during the installation of the SDK."
else
	echo -e "${COLOR_Yellow} ALREADY INSTALLED${COLOR_Wipe}"
fi
echo

F_PressEnter
