#!/bin/bash
. scripts/functions    
clear

F_PleaseWait

curl -s http://developer.android.com/sdk/index.html > sdk.html
SDK_LINK=$(grep -i linux-tools sdk.html | awk -F'"' '{print $6}')
SDK_ZIPNAME=$(echo $SDK_LINK | awk -F'/' '{print $5}')
rm sdk.html

F_Download $SDK_ZIPNAME $SDK_LINK SDK

# Extract SDK
SDK_Install=0

if [ ! -d "android-sdk-linux" ]; then
	SDK_Install=1
	echo -n -e "\n Extracting SDK... "
	tar zxvf $SDK_ZIPNAME 2>/dev/null 1>/dev/null
	
	if [ $? -eq 0 ]; then
		echo -e "${COLOR_Green}SUCCESS${COLOR_Wipe}"
	else
		echo -e "${COLOR_Red}ERROR${COLOR_Wipe}\n"
		echo -e " ${COLOR_Red}Error when extracting SDK.${COLOR_Wipe}\n"
		F_PressEnter
		exit
	fi
fi

sudo chmod -R 777 android-sdk-linux

# Download SDK-Tools

curl -s http://dl-ssl.google.com/android/repository/repository-8.xml > sdktools.html
SDKTOOLS_ZIPNAME=$(grep -i build-tools_r sdktools.html | grep -i linux | awk -F'>' '{print $2}' | awk -F'<' '{print $1}' | awk 'END {print}')
SDKTOOLS_LINK="http://dl-ssl.google.com/android/repository/$SDKTOOLS_ZIPNAME"
SDKTOOLS_VERSION=$(echo $SDKTOOLS_ZIPNAME | awk -F'r' '{print $2}'  | awk -F'-' '{print $1}')


F_Download $SDKTOOLS_ZIPNAME $SDKTOOLS_LINK build-tools


# Extract SDK-Tools

if [ ! -d android-sdk-linux/build-tools ]; then
	SDK_Install=1
	echo -n -e "\n Extracting SDK build-tools... "
	mkdir android-sdk-linux/build-tools/$SDKTOOLS_VERSION 2>/dev/null
	unzip -qq -o $SDKTOOLS_ZIPNAME -d android-sdk-linux/build-tools
	
	if [ $? -eq 0 ]; then
		sudo chmod -R 777 android-sdk-linux/build-tools
		mv -f android-sdk-linux/build-tools/* android-sdk-linux/build-tools/$SDKTOOLS_VERSION
		echo -e "${COLOR_Green}SUCCESS${COLOR_Wipe}"
	else
		echo -e "${COLOR_Red}ERROR${COLOR_Wipe}\n"
		echo -e " ${COLOR_Red}Error when extracting SDK build-tools.${COLOR_Wipe}\n"
		F_PressEnter
		exit
	fi
fi


# SDK Platform Tools

SDKPTOOLS_ZIPNAME=$(grep -i platform-tools_r sdktools.html | grep -i linux | awk -F'>' '{print $2}' | awk -F'<' '{print $1}' | awk 'END {print}')
SDKPTOOLS_LINK="http://dl-ssl.google.com/android/repository/$SDKPTOOLS_ZIPNAME"
rm sdktools.html 2>/dev/null


F_Download $SDKPTOOLS_ZIPNAME $SDKPTOOLS_LINK platform-tools

# Extract SDK Platform Tools

SDK_Platformtool=0

if [ ! -d android-sdk-linux/platform-tools ]; then
	SDK_Install=1
	echo -n -e "\n Extracting SDK platform-tools... "
	unzip -qq -o $SDKPTOOLS_ZIPNAME -d android-sdk-linux/
	
	if [ $? -eq 0 ]; then
		sudo chmod -R 777 android-sdk-linux/platform-tools
		echo -e "${COLOR_Green}SUCCESS${COLOR_Wipe}"
	else
		SDK_Platformtool=1
		echo -e "${COLOR_Red}ERROR${COLOR_Wipe}\n"
		echo -e " ${COLOR_Red}Error when extracting SDK platform-tools.${COLOR_Wipe}\n"
		F_PressEnter
		exit
	fi
fi

if [ $SDK_Platformtool == 0 ]; then
	if ! grep -q -i "export PATH=" ~/.bashrc; then
		echo >> ~/.bashrc
		echo "export PATH=$(pwd)/android-sdk-linux/tools:$PATH" >> ~/.bashrc
	elif ! grep -q -i "=$(pwd)/android-sdk-linux/tools" ~/.bashrc && ! grep -q -i "$(pwd)/android-sdk-linux/tools:" ~/.bashrc  && ! grep -q -i ":$(pwd)/android-sdk-linux/tools" ~/.bashrc; then
		var=$(grep -i "export PATH=" ~/.bashrc)
		sed -i '/export PATH=/d' ~/.bashrc
		echo $var":$(pwd)/android-sdk-linux/tools" >> ~/.bashrc
	fi
	 
	if ! grep -q -i "export PATH=" ~/.bashrc; then
		echo >> ~/.bashrc
		echo "export PATH=$(pwd)/android-sdk-linux/platform-tools:$PATH" >> ~/.bashrc
	elif ! grep -q -i "=$(pwd)/android-sdk-linux/platform-tools" ~/.bashrc && ! grep -q -i "$(pwd)/android-sdk-linux/platform-tools:" ~/.bashrc  && ! grep -q -i ":$(pwd)/android-sdk-linux/platform-tools" ~/.bashrc; then
		var=$(grep -i "export PATH=" ~/.bashrc)
		sed -i '/export PATH=/d' ~/.bashrc
		echo $var":$(pwd)/android-sdk-linux/platform-tools" >> ~/.bashrc
	fi
fi

source ~/.bashrc

if [ $SDK_Install == 1 ]; then
	echo -e "\n ${COLOR_Green}The installation of SDK was successful.${COLOR_Wipe}"
else
	echo -e "\n ${COLOR_Yellow}SDK is already installed.${COLOR_Wipe}"
fi
echo

F_PressEnter
