#!/bin/bash
. scripts/functions

if [ ! -f ~/bin/repo ]; then
	echo -e -n  "\n The ${COLOR_Yellow}repo${COLOR_Wipe} command does not seem installed. 
	Install ? [Recommended]
	(Y)es, (N)o: "
		
	read choice

	case $choice in	
		[Yy]* ) 
			echo -n -e "\n Installing repo... "

			mkdir -p ~/bin
			wget -q "http://commondatastorage.googleapis.com/git-repo-downloads/repo"
			
			if [ -f repo ] && [ $(F_SizeOf repo) -gt 0 ]; then
			
				mv repo ~/bin/repo
				chmod a+x ~/bin/repo
			
				if [ -f ~/bin/repo ]; then
					echo -e "${COLOR_Green}SUCCESS${COLOR_Wipe}"

					if [ ! -f ~/.bashrc ]; then
						echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
					else
						if ! grep -q -i "export PATH=" ~/.bashrc; then
							echo >> ~/.bashrc
							echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
						elif ! grep -q -i "=~/bin" ~/.bashrc && ! grep -q -i "~/bin:" ~/.bashrc  && ! grep -q -i ":~/bin" ~/.bashrc; then
							var=$(grep -i "export PATH=" ~/.bashrc)
							sed -i '/export PATH=/d' ~/.bashrc
							echo $var':~/bin' >> ~/.bashrc
						fi
					fi
					source ~/.bashrc
				else
					echo -e "${COLOR_Red}ERROR${COLOR_Wipe}"
					rm -f repo 2>/dev/null
					F_PressEnter
					exit 1
				fi
			else
				echo -e " ${COLOR_RED}ERROR${COLOR_Wipe}"
				echo -e " Cannot download repo file\n"
				rm -f repo
				F_PressEnter
				exit 1
			fi
			;;
				
		[Nn]* )
			echo -e " Repo installation... ${COLOR_Cyan}Ignored${COLOR_Wipe}"
			exit 2
			;;
				
		* )
			echo -e " Wrong value... ${COLOR_Cyan}Ignored${COLOR_Wipe}"
			exit 2
			;;
	esac
else
	exit 4
fi
exit 0
