#!/bin/bash
. scripts/functions
clear

echo
echo -e " Device: ${COLOR_Yellow}empty${COLOR_Wipe} | Branch: ${COLOR_Yellow}empty${COLOR_Wipe}"
echo -e " Repo path: ${COLOR_Yellow}empty${COLOR_Wipe}"



while :
do

  clear


  echo 
	clear
	echo -e "\n ==============================================================="
	echo -e " ${COLOR_Blue}$1 $2${COLOR_Wipe} # by GalaxyUser [${COLOR_Yellow}xda-developers.com${COLOR_Wipe}]"
	echo -e " ==============================================================="
	echo "    -> [Sync/Build CyanogenMod sources]"
	echo
	echo "    1) Change Repo path"
	echo "    2) Change branch"
	echo "    3) Change device"
	echo
	echo "    4) View git config"
	echo "    5) Sync sources"
	echo "    6) Build repo"
	echo 
	echo "    e) Return to main menu"
	echo
	echo -n " Enter option: "
	
	read choice

		case $choice in
		
		1 ) scripts/change_repo_path
			;;
			
		2 ) scripts/change_cm_branch
			;;
			
		3 ) scripts/change_device
			;;
			
		4 ) scripts/view_git_config
			;;
			
		5 ) scripts/sync_cm_sources
			;;
			
		5 ) scripts/build_cm_sources
			;;
		
		[Ee]* )
			exit 1
			;;
		
		* ) ;;
		esac

done
